language: node_js
node_js:
    - "0.12"
before_install:
    - npm install -g grunt-cli
    - npm install -g bower
    - bower install
    - npm update
    - bower update
notifications:
    email:
        on_success: change
        on_failure: change
env:
    global:
        - secure: UEXAYK3f2bGw7YmWsMlpAydto7sYu+qd9sUA6J3qvXH+QEan6fc8Yo831hYfsUe66WW6Oz4vp2BwE/r+gQBjJgqpxyq1N4T/7b6p1x7KUwXms6rM8GZfswfUOdlTkIzlWwXyAsnSCuqUlfuT5lKsHi5yurDBgTMVWcSAdi0BQjc=
        - secure: Ir46Mp7v2T1QLfuVRzZbCQ1NrLj8q8kiVzAgNsNDeuuBZGlOLJSfOeZ4zbOy/FdXe0iUSw/K5eGaSIKyQdoDJiNdXAm3tOWo0TOfwc0VIvWLEABYcLNxFiHVO7Ju+hUJKFwJgmOo39fmsi63gYNDrEw5+naOB5FQZgCkRO8oCg==
sudo: false
cache:
    directories:
        - node_modules
        - src/agrc
        - src/bootstrap/
        - src/components-jasmine/
        - src/dgrid/
        - src/dgauges/
        - src/dijit/
        - src/dojo/
        - src/dojox/
        - src/esri/
        - src/favico.js/
        - src/ijit/
        - src/jasmine-favicon-reporter/
        - src/jasmine-jsreporter/
        - src/jquery/
        - src/ladda-bootstrap/
        - src/mustache/
        - src/proj4/
        - src/put-selector/
        - src/spin.js/
        - src/spinjs/
        - src/stubmodule/
        - src/util/
        - src/xstyle/
